### ISSUE TITLE
6.2.6 Leaves empty secure path, breaks playbook

### ISSUE THREAD

**Issue by Mountainerd** [florianutz/Ubuntu1604-CIS#8] opened 2018-03-21 23:41 UTC
When running against a Ubuntu 16.04.4 machine that was upgraded from a clean 16.04.3 installation, 6.2.6 doesn't update secure path with anything. The resulting /etc/sudoers file results in this on line 11:
```
Defaults        secure_path=""
```
At this point, Ansible is unable to continue and the connection is broken.

**Comment by florianutz** [comment] 2018-03-22 06:39
Can you please tell me what the line looked like before?

**Comment by Mountainerd** [comment] 2018-03-22 14:07
I'm not at my machine right now but I believe it was something like:
```
/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
```

**Comment by Mountainerd** [comment] 2018-03-22 16:01
I've also taken the fixsudo.sh script and run it outside of Ansible on a Ubuntu 16.04.4 box and it outputs nothing out of the ordinary.

**Comment by florianutz** [comment] 2018-03-22 20:27
I am not able to reproduce this behaviour on my testing environments. I will extend the script with some debugging output to identify the possible reason on your system.
But you have brought me to an important point. I have to validate the return value and skip the modification task if it is empty.

**Comment by florianutz** [comment] 2018-03-22 21:53
Now i added two things in the _dev_ branch:
- the modification task will skip if the shellscript returns an empty value
- the `fixsudo.sh` now accept a parameter `fixsudo.sh debug` for debugging output

Can you please run the script with the debug parameter. Maybe we can identify your problem.

**Comment by Mountainerd** [comment] 2018-03-23 15:32
I'll be happy to run it but I want to ensure that what I said earlier is clear. The script that I currently have (not the one in the _dev_ branch) outputs the text inside the quotes of secure path. Let me pull down the script, run it, and get you the output.

**Comment by Mountainerd** [comment] 2018-03-23 15:54
I noticed one difference out of the gate with the scripts. The version I have downloaded has `for i in ${sudopath[@]}` while the one in the dev branch opts to go with `for i in ${sudopath[*]}`. 

Here's the output of the debug of the fixsudo.sh in the dev branch:
```
root@ubuntu16044-base:~# ./fixsudo.sh debug

Debug secure_path: Defaults     secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
Debug sudopath: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Debug result: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

I also swapped out the [*] in the initial for statement for a [@] and achieved the same result.

**Comment by florianutz** [comment] 2018-03-23 21:05
The debug output returns the right values. I am not able to reproduce an empty `secure_path=""` on my systems.
Maybe there is an issue with your ansible version. My current environment use ansible 2.4.3.0 but it should also work with older versions.
Possibly you could debug the issue on your system and let me know what was wrong.
e.g. run `ansible-playbook playbook.yml --tags "rule_6.2.6" -vvv` and try to find the reason why the replace task does not work on your system.

**Comment by Mountainerd** [comment] 2018-03-26 04:35
I'm using the same environment (2.4.3.0). Digging through the -vvv output, it turns out the script was returning multiple lines, so the [0] on line 231 in section6.yml was the culprit. The playbook was running fine in that 0 would return nothing (as you see below) but if I replace it with [1], it completes file and now the line in /etc/sudoers is correct. 

Output that lead to solution:
```
ok: [swarm1] => {
    "changed": false,
    "rc": 0,
    "stderr": "Shared connection to swarm1 closed.\r\n",
    "stdout": "\r\n/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\r\n",
    "stdout_lines": [
        "",
        "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ]
}
```

Solution in section6.yml on line 231 (change 0 to 1):
```
    line: '\1"{{ fixsudo.stdout_lines[1] }}"'
```

**Comment by florianutz** [comment] 2018-03-26 21:12
I think I fixed the issue by switching to the shell command module. May you be able to test again the dev branch?

**Comment by Mountainerd** [comment] 2018-03-27 20:41
Hey Florian! I can confirm that section6.yml that you have in the _dev_ branch works as expected. Thank you for working with me on figuring out what's going on and hope I was able to help you figure out what to target quicker. This is a great playbook and is saving me so much time! Very much appreciated!

**Comment by florianutz** [comment] 2018-03-27 22:20
I'm glad it's useful for you. Please come back to me if you have further questions. I merged the fix and will close the issue.

**Closed by florianutz** 2018-03-27 22:20 UTC
